{% set name = "nbserverproxy" %}
{% set version = "0.8.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c8afb9502e425bc007e56207fac3f0caed0bf300fc0fcfdc8a174106d513d997" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - notebook

test:
  imports:
    - nbserverproxy

about:
  home: https://github.com/jupyterhub/nbserverproxy
  license: BSD 3-Clause
  license_family: BSD
#  license_file: LICENSE
  summary: Jupyter server extension to proxy web services

extra:
  recipe-maintainers:
    - ocefpaf
    - lsetiawan
