travis:
  secure:
    BINSTAR_TOKEN: Mi0FwEABziGdxSeCkXWEQSL0FxBcrRUT3txpU+CCaur5ab5lIfnLOibgGt4rVuZkfty/kb64gBR1daaHgOYEjJpQidi6tXzZ5WNdI0oWJ8n/MXQNwxJDZ73sg3hOoRQoavr89x0RApz5f/PJP9AU/tW136/9gAIeAnSR1ihNzYdCQ7slQreKI1J0I94wm+2SoGuglI0obAbd/Q6fA426iYjEgRN6fMvTrBpd4JrW/PbEeDozXpRYQe1FvZY4zsec3YSoD1IhT+ZogLWQ7x3YoLDENQAU46m6OJhUmnZIoMahvAmNARJKJQHTpr/5nWiBfiT6g68VpqbBCf6m11sPBdHlBsEzhV1Kukyh87oiynP2MBltQdQ020j9PticQJdyV+f5w0gPwRR+FdpVRJShBUjW+nwPEiTqXCo69+zgUjrc0wVwW54CdxyYv069f0tPS7GCz8W6fFSTMwyn+aA/IhIr4JocH86H18TTpsoZIgKGcvcc6UbtyF57YyRIYd32t3JB6mKDyzve5wSTzg8Qi9Z7s23fvBjtkZXwt7dYIuSBjEncjOQfih0Kh9cTILhn6IgJah16zxX+e1vZ8r1vVgHULpbAK23dAOmDtqVBKPwF/aPChBX6uOZiOdNLFZv0pBf7q9nc8QAN6Tf7eB5mbkk3dkeZSdLFPonrUcso/ZA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
